### ISSUE TITLE
Deprecate ndndump

### ISSUE THREAD

**Issue by yoursunny** [named-data/ndndump#3]
Deprecate ndndump repository, and refer users to [ndn-tools](https://github.com/named-data/ndn-tools).

**Comment by cawka** [comment]
Which actions should I do for this deprecation?  Put a note in README.md file or something else?

**Comment by yoursunny** [comment]
This issue is blocked by [ndn-tools issue 2855](http://redmine.named-data.net/issues/2855).
This shall be completed in the same manner as [ndn-tlv-ping issue 9](https://github.com/named-data/ndn-tlv-ping/issues/9).

**Comment by yoursunny** [comment]
This issue is no longer blocked.

**Comment by eric135** [comment]
I will work on this issue.
